AlertaDengue/dados/templates/alerta.html

High risk should be at the top

Reverse legend

---

.gitignore
AlertaDengue/dados/management/commands/sync_geojson.py
AlertaDengue/dados/templates/alert_state/map.html
AlertaDengue/dados/views.py

resolves #55 
The command bellow gets the geojson from database of all cities and save as a geojson file into static folder.
```python
python AlertaDengue/manage.py sync_geojson
```

Management command sync_geojson added.

---

AlertaDengue/dados/dbdata.py
AlertaDengue/dados/templates/alert_state/map.html
AlertaDengue/dados/templates/alerta.html
AlertaDengue/dados/templates/alerta_municipio.html
AlertaDengue/dados/templates/main.html
AlertaDengue/dados/templates/my_bootstrap3_base.html
AlertaDengue/dados/templates/series_plot.html
AlertaDengue/dados/templates/total_series.html
AlertaDengue/dados/templatetags/series.py
AlertaDengue/dados/views.py
AlertaDengue/static/css/infodengue.css
sql/create_historico_casos.sql
sql/create_uf_total_chik_view.sql
sql/episem.sql

Resolves #46 

---

AlertaDengue/dados/templates/main.html
AlertaDengue/dados/views.py

Adicionda a informação sobre a última semana nos cards de estados na tela inicial

Fixes #101 

---

AlertaDengue/dados/dbdata.py

Falta aplicar valores de níveis e prt1

Fixes partially #25

---

AlertaDengue/dados/dbdata.py
AlertaDengue/dados/maps.py
AlertaDengue/dbf/migrations/0002_dbfchunkedupload.py

@flavioamieiro 
basicamente esta é a solução. porém não consegui analisar os resultados dos gráficos para ver se está tudo ok.
Consigo fazer a análise dos resultados somente amanhã de manhã.

Fixes #128

---

AlertaDengue/AlertaDengue/settings.py
AlertaDengue/dbf/sinan.py

Improves logging when importing DBFs

---

AlertaDengue/dados/dbdata.py
AlertaDengue/dados/templates/alert_base.html
AlertaDengue/dados/templates/alert_state/map.html
AlertaDengue/dados/templates/report_filter_city.html
AlertaDengue/dados/templates/report_filter_report_type.html
AlertaDengue/dados/templates/report_filter_state.html
AlertaDengue/dados/templates/report_state.html
AlertaDengue/dados/urls.py
AlertaDengue/dados/views.py
AlertaDengue/static/css/infodengue.css
AlertaDengue/templates/my_bootstrap4_base.html

https://infostaging.dengue.mat.br/alerta/RJ/dengue

Resolves #193

---

.circleci/config.yml

Added initial configuration for circleci

---

AlertaDengue/requirements-conda.txt
AlertaDengue/requirements.txt

Dentro deste PR:
Arquivos requeriments ajustado
Resolves #218

ajuste in files requeriments

---

.circleci/config.yml
AlertaDengue/requirements-dev.txt

Dentro deste PR: WIP
Ajuste em Arquivo com a Configuração do CiclerCI e requirements-dev.txt
Resolves #227

WIP: implement in file configuration the cicler CI for python 3.7 and 3.6

---

.circleci/config.yml
AlertaDengue/requirements-dev.txt

Reverts AlertaDengue/AlertaDengue#228

Revert "WIP: implement in file configuration the cicler CI for python 3.7 and 3.6"

---

ci/settings-demo.ini
dockerfile-demo-DB

- Foi criado um path para o arquivo settings-demo.ini para evita que os dados fique expostos.
- Foi feito um update no dockerfile e renomeado para dockerfile_demoDB. (Para auxiliar na criação do ambiente de desenvolvimento).

Upgrade dockerfile-demo-DB and path ci settings-demo.ini

---

CONTRIBUTING.md

Dentro deste PR:
Arquivo inserido "CONTRIBUTING.md"
Atende a #213

Issue213 configure development environment

---

.gitignore
AlertaDengue/dados/dbdata.py
AlertaDengue/dados/views.py

Refactoring

---

AlertaDengue/dados/charts.py
Dockerfile

- Implementations in charts hoverinfo 'popup' concluded, Closes#244

Popup format changes completed-issue#244

---

AlertaDengue/dados/charts.py
AlertaDengue/dados/templates/main.html
AlertaDengue/dados/templatetags/series.py
AlertaDengue/dados/views.py

- Alterado os Gráficos na Home de HighCharts to Plotly.
- Modificado a exibição de 1 linha e 3 colunas to 3 linhas e 1 coluna, e as dimensões de cada Chart.
- Restam poucas alterações para a conclusão; Subtitles por nome da disease, formating datetime, etc.
- Resolves #246
This is a snapshot of the charts:

Migrate plotly home/ issue#246

---

AlertaDengue/environment.yml
AlertaDengue/requirements.txt

- Resolves PR #274
- Pinned latest version before remove packages dependencies of django.

Pinned django version to 2.2.8

---

AlertaDengue/AlertaDengue/settings.py
staging-compose.yml

- Modificado o valor de DEBUG (string para boolean) em settings.py
- Inserido volumes STAGING_DATA_DIR e expose ports para o stging_db

Bug-fix debug_false

---

AlertaDengue/AlertaDengue/celery.py
AlertaDengue/AlertaDengue/urls.py

- Finaliza o merge do PR #284 
- Removido from __future__ import unicode para python2
- Removido Try_Exception de url_admin e substituido o url() para path()

Resolves PR_284

---

AlertaDengue/AlertaDengue/settings.py
Makefile

- Finaliza o merge do PR #284
- Removido as variáveis duplicadas de conexão a base de dados.

Deleted duplicate DATABASES variables in settings.py file

---

AlertaDengue/dados/charts.py

- Mudado o eixo de plotagem de threshold para incidências.

Modificado a plotagem de threshold em report_city

---

Dockerfile-flower
docker-compose.yml
staging-compose.yml

Inserted into docker-compose flower-celery

---

AlertaDengue/AlertaDengue/settings.py
AlertaDengue/dados/templates/alert_state/age.html
AlertaDengue/dados/templates/alert_state/date.html
AlertaDengue/dados/templates/alert_state/disease.html
AlertaDengue/dados/templates/alert_state/epiyears.html
AlertaDengue/dados/templates/alert_state/gender.html
AlertaDengue/dados/templates/state_cities.html

- Inserido nos highcharts a descrição das datas selecionadas.
- Modificado o layout centralizando o campo da descrição do filtro.

Modified State page view

---

docker/docker-compose.yml
docker/staging-compose.yml

- Changed to Docker-celery in compose files

Fixes error in celery-worker

---

docker/docker-compose.yml
docker/staging-compose.yml

Reverts AlertaDengue/AlertaDengue#322

Revert "Atualiza master"

---

docker/Dockerfile
docker/Dockerfile-celery
docker/docker-compose.yml
docker/prepare_permission.sh
docker/staging-compose.yml

- Inserido args para host_id e host_gid no docker-compose.
- Inserido o script para a criação do user and group no arquivo dockerfile.
- Modificado de celery para deploy o groupname.

Fixes dbf load to save into media_root

---

AlertaDengue/dbf/sinan.py
docker/staging-compose.yml

- Inserido no serviço celery-worker em staging-compose psql_port
- Inserido variável port no arquivo sinan.py para conexão com a db

Inserted port of connection for celery

---

docker/prepare_permission.sh
docker/staging-compose.yml

- Resolve o erro de salvar o arquivo dbf em imported_files após a inserção no banco

Inserted Volume imported_files in staging_web

---

AlertaDengue/dados/templates/alert_base.html
AlertaDengue/dados/views.py

Fixed the redirect link from alertamrj to report_city

---

AlertaDengue/AlertaDengue/settings.py
AlertaDengue/dados/templates/503.html
environment-3.7.yml

- Resolves #336 
- Resolves #335 
- Created new maintenance template.
- Fixes  security vulnerability in Django version.
Page 503:

Create maintenance mode

---

AlertaDengue/ad_main/__init__.py
AlertaDengue/ad_main/celeryapp.py
AlertaDengue/run_celery_worker.sh

Fixes load celery application

---

AlertaDengue/dados/charts.py
AlertaDengue/dados/dbdata.py
AlertaDengue/dados/urls.py
AlertaDengue/dados/views.py

Add Rio Grande do Sul

---

AlertaDengue/dados/charts.py
AlertaDengue/dados/dbdata.py
AlertaDengue/dados/urls.py
AlertaDengue/dados/views.py

Add Maranhão

---

AlertaDengue/dados/dbdata.py
AlertaDengue/dbf/sinan.py

Fix geocodes entry in the Notificacao table

---

AlertaDengue/dados/charts.py
AlertaDengue/dados/dbdata.py
AlertaDengue/dados/views.py

Fix range series in the charts on home-page

---

.github/workflows/linux.yml
.gitignore
AlertaDengue/api/db.py
AlertaDengue/api/views.py
AlertaDengue/dados/views.py

Resolves #370 
Foi modificado o comportamento para utilizar a tabela historico_alerta ao invés de mrj.

Standardize the query of the APIs

---

AlertaDengue/dados/dbdata.py
AlertaDengue/dados/views.py

Fixes week values

---

AlertaDengue/dados/charts/home.py
AlertaDengue/dados/dbdata.py
AlertaDengue/dados/urls.py
AlertaDengue/dados/views.py

Add Santa Catarina

---

AlertaDengue/dados/views.py

Fixes incidence numbers

---

AlertaDengue/forecast/models.py

- Closes #270
- Ajustado os campos da tabela de ForecastModel e criado uma nova tabela Forecast relacional;

Changed and validate table fields to app_forecast

---

.github/workflows/linux.yml
AlertaDengue/dados/views.py
Makefile
environment-3.7.yml

Create new variable for filter n_dengue

---

AlertaDengue/gis/management/commands/sync_geofiles.py
environment-3.7.yml
requirements.txt

Fixes processing sync_geofiles

---

.pre-commit-config.yaml
environment-3.7.yml
requirements.txt

Resolves dependencies

---

AlertaDengue/dbf/sinan.py

Bugfixes sinan

---

.github/workflows/linux.yml
AlertaDengue/ad_main/settings.py
AlertaDengue/dbf/admin.py
AlertaDengue/dbf/mailing_partner.py
AlertaDengue/dbf/management/commands/send_mail.py
AlertaDengue/dbf/models.py
AlertaDengue/dbf/templates/email_secretarias.txt
AlertaDengue/dbf/tests/test_mailing_partner.py
AlertaDengue/dbf/tests/test_models.py
AlertaDengue/dbf/tests/test_validation.py
AlertaDengue/dbf/tests/test_views.py
Makefile
docker/Dockerfile
docker/Dockerfile-dev
docker/cron-sendmail
docker/entrypoint.sh

Create service to automate email send

---

.gitignore
AlertaDengue/ad_main/settings.py
AlertaDengue/dados/charts/home.py
AlertaDengue/dados/dbdata.py
AlertaDengue/dados/views.py
docker/Dockerfile-postgres
docker/staging-compose.yml
environment-3.8.yml
environment-dev.yml
requirements-dev.txt
requirements.txt

This PR:
- improves and fixes docstrings
- adds profiling for development
- uses postgis image used by staging from the official source
- adds a missing dependency

Improve docstrings and add profiling for development

---

AlertaDengue/dados/charts/home.py
docker/Dockerfile-postgres

Fixes insertion of new states in the homepage charts

---

.dockerignore
Makefile
docker/Dockerfile
docker/Dockerfile-celery
docker/Dockerfile-dev
docker/docker-compose.yml
docker/staging-compose.yml
setup.py

- Fix flower dependency error
- Modifies the installation of packages to mamba in dockerfiles
- Reduces image size and build time
- Created the network in staging-compose file

Fix docker-compose and modify the makefile

---

AlertaDengue/dados/dbdata.py
AlertaDengue/dados/tests/test_dbdata.py
AlertaDengue/dados/views.py
AlertaDengue/gis/geotiff.py
AlertaDengue/gis/mapfile.py
docker/Dockerfile-dev

Change queries to parameters table

---

AlertaDengue/dados/dbdata.py

Fixes cache name for charts

---

AlertaDengue/dados/charts/home.py
AlertaDengue/dados/dbdata.py
AlertaDengue/dados/views.py

Improve home page charts

---

AlertaDengue/dbf/utils.py

Fixes expected fields for the upload dbf

---

AlertaDengue/api/db.py

- Resolves #502.
- Add get_suffix function for get tables names.

Bugfix get chikungunya disease for API

---

AlertaDengue/ad_main/settings.py
AlertaDengue/dados/charts/home.py
AlertaDengue/dados/dbdata.py
AlertaDengue/dados/templates/components/home/carousel.html
AlertaDengue/dados/templates/components/home/collapse.html
AlertaDengue/dados/templatetags/home_components.py
AlertaDengue/dados/views.py
docker/sql/create_hist_uf_diseases_view.sql

- Refers #481
- Update query to create_hist_uf_diseases_view

Update materialized view for homepage

---

AlertaDengue/ad_main/settings.py
AlertaDengue/dados/dbdata.py
AlertaDengue/dbf/sinan.py
AlertaDengue/dbf/utils.py
AlertaDengue/dbf/validation.py
conda/environment.yaml
poetry.lock
pyproject.toml

Update DBF upload

---

.github/workflows/linux.yml
AlertaDengue/gis/management/commands/sync_geofiles.py
AlertaDengue/runwsgi.sh
Makefile
docker/Dockerfile-base
docker/Dockerfile-web
docker/compose-dev.yaml
docker/compose-prod.yaml
docker/cron-tasks

- Closes #532
A broken path was stopping send_mail service.

Fix path in Docker cron-tasks

---

docker/sql/create_hist_uf_diseases_view.sql
docker/sql/create_uf_total_chik_view.sql
docker/sql/create_uf_total_zika_view.sql

Update materialized views

---

Makefile
docker/Dockerfile-base
docker/Dockerfile-dev
docker/Dockerfile-web
docker/entrypoint.sh
docker/test.sh

Bugfix makefile test-staging command call

---

AlertaDengue/dbf/db.py
AlertaDengue/dbf/sinan.py
AlertaDengue/dbf/templates/dbf_upload.html
AlertaDengue/dbf/utils.py
setup.py

Bugfix sinan upload

---

AlertaDengue/dbf/sinan.py
AlertaDengue/dbf/utils.py
setup.py

Fix special character insertion error from SINAN

---

AlertaDengue/dbf/utils.py

[Bugfix] Dataframe key error in _parse_fields

---

docker/postgres/sql_history/insert_probable_case_into_hist_alerta.sql

- Resolve #527
``` 
dengueadmin@localhost:dengue> \d "Municipio"."Historico_alerta"
+---------------------+------------------------+-----------------------------------------------------------------------------------+
| Column              | Type                   | Modifiers                                                                         |
|---------------------+------------------------+-----------------------------------------------------------------------------------|
| data_iniSE          | date                   |  not null                                                                         |
| SE                  | integer                |  not null                                                                         |
| casos_est           | real                   | …
```

Add script sql to update hist_alerta table

---

AlertaDengue/dados/templatetags/home_components.py

Sort states by name, not initials

---

AlertaDengue/dados/templates/report_city.html
AlertaDengue/dados/templates/services_api.html
AlertaDengue/locale/en/LC_MESSAGES/django.po

Update the API dictionary

---

AlertaDengue/dados/templates/components/report_state/report_state_charts.html

BUGFIX: url state report

---

AlertaDengue/dados/templates/about.html
AlertaDengue/dados/templates/components/main/footer.html
AlertaDengue/dados/templates/main.html
AlertaDengue/dados/templates/team.html
AlertaDengue/dados/templatetags/footer_components.py
AlertaDengue/templates/base.html

feat(template) Add github sponsors card

---

AlertaDengue/dados/templatetags/footer_components.py
poetry.lock

Update linting package versions

---

poetry.lock
pyproject.toml

chore(pyproject): Update django version

---

.containers-sugar.yaml
.github/workflows/linux.yml
.makim.yaml
containers/compose.yaml

feat(postgres): Add new volume to production database

---

AlertaDengue/dbf/utils.py
containers/web/Dockerfile
poetry.lock
pyproject.toml

Fix pata_parsing function to handle float values

---

AlertaDengue/api/db.py
AlertaDengue/api/urls.py
AlertaDengue/api/views.py
AlertaDengue/dados/dbdata.py
AlertaDengue/dados/tasks.py
AlertaDengue/dados/templates/alert_state/age.html
AlertaDengue/dados/templates/alert_state/date.html
AlertaDengue/dados/templates/alert_state/disease.html
AlertaDengue/dados/templates/alert_state/epiyears.html
AlertaDengue/dados/templates/alert_state/gender.html
AlertaDengue/dados/templates/alert_state/map.html
AlertaDengue/dados/templates/state_cities.html
AlertaDengue/dados/templatetags/alert_state.py
AlertaDengue/dados/urls.py
AlertaDengue/dados/views.py
AlertaDengue/gis/management/commands/sync_geofiles.py

```postgresql
UPDATE "Dengue_global"."CID10"
SET codigo = 'A92.0'
WHERE codigo = 'A920';
```
---
```postgresql
UPDATE "Municipio"."Notificacao"
SET cid10_codigo = 'A92.0'
WHERE cid10_codigo = 'A920';
```

revert: Recent updates to alerta_state_view

---

AlertaDengue/dados/dbdata.py
AlertaDengue/dados/models.py
AlertaDengue/dados/views.py
containers/postgres/schemas/schemas_dengue.sql

chore(sql): move regional & macroregional info to Municipios table; update references

---

.github/workflows/linux.yml
.github/workflows/release.yaml
AlertaDengue/upload/sinan/utils.py
AlertaDengue/upload/tasks.py
AlertaDengue/upload/views.py

fix error: SINANUploadFatalError("Error populating temporary table: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'")

fix(upload): int(None) error on df.SEM_PRI parse_data

---

AlertaDengue/dados/charts/home.py

fix(charts): fix epiweek on home's stack_chart

---

.gitignore
AlertaDengue/ad_main/settings.py
AlertaDengue/api/db.py
AlertaDengue/dados/templates/alert_state/date.html
AlertaDengue/dados/templates/alert_state/disease.html
AlertaDengue/dados/templates/alert_state/epiyears.html
AlertaDengue/dados/templates/alert_state/map.html
AlertaDengue/dados/templates/components/home/charts.html
AlertaDengue/dados/templates/main.html
AlertaDengue/dados/templates/state_cities.html
AlertaDengue/dados/templatetags/alert_state.py
AlertaDengue/dados/views.py
AlertaDengue/locale/en/LC_MESSAGES/django.po
AlertaDengue/locale/es/LC_MESSAGES/django.po
AlertaDengue/templates/base.html

fix(reports): fix week cases on state reports & more

---

AlertaDengue/dados/dbdata.py
AlertaDengue/dados/views.py

fix(alerts): use most recent 'SE' to set the dates on city and state Alert views
